name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org5c366e27.crm.dynamics.com'
        user-name: 'admin@CRM298449.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org5c366e27.crm.dynamics.com'
        user-name: 'admin@CRM298449.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: DentaQuest_POC_PDL_Verification
        solution-output-file: out/exported/DentaQuest_POC_PDL_Verification.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/DentaQuest_POC_PDL_Verification.zip
        solution-folder: out/solutions/DentaQuest_POC_PDL_Verification
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/DentaQuest_POC_PDL_Verification
        solution-target-folder: solutions/DentaQuest_POC_PDL_Verification
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
